name: 'Bugster Bot'
description: 'Bugster Bot, a paranormal investigation and removal service for bugs and bad practices'
inputs:
  ATLASSIAN_API_TOKEN:
    description: 'Atlassian API Token'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API Key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests openai python-dotenv

    - name: Run bot.py
      env:
        BITBUCKET_PR_ID: ${{ inputs.BITBUCKET_PR_ID }}
        BITBUCKET_BRANCH: ${{ inputs.BITBUCKET_BRANCH }}
        BITBUCKET_PR_DESTINATION_BRANCH: ${{ inputs.BITBUCKET_PR_DESTINATION_BRANCH }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
      run: python bot.py