name: 'Bugster Bot'
description: 'Bugster Bot, a paranormal investigation and removal service for bugs and bad practices'
inputs:
  BRANCH:
    description: 'Branch'
    required: true
  DESTINATION_BRANCH:
    description: 'Destination Branch'
    required: true
  EXTENTIONS_TO_CHECK:
    description: 'Extensions to check separated with commas, e.g.: py,js,cs'
    required: true
  ATLASSIAN_API_TOKEN:
    description: 'Atlassian API Token'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API Key'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install requests openai python-dotenv

    - name: Run bot.py
      shell: bash
      env:
        BRANCH: origin/${{ inputs.BRANCH }}
        DESTINATION_BRANCH: origin/${{ inputs.DESTINATION_BRANCH }}
        GITHUB_REPOSITORY: ${{ inputs.repository }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
        ATLASSIAN_API_TOKEN: ${{ inputs.ATLASSIAN_API_TOKEN }}
      run: python bot.py cs
