name: Bash Script
on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name : Fetch all the branches
        run: git fetch --all

      - name: Run Bash script
        run: bash diff.sh feature/001 develop