name: Bash Script

on:
  workflow_dispatch:

jobs:
  bash-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch all the branches
        run: git fetch --all
  
      - name: Debug branches
        run: git branch -a


      - name: Run Bash script
        run: bash diff.sh feature/001 origin/develop

      - name: Print Github Contenxt json
        run: echo "${{ toJson(github) }}"
