name: Run Bugster Bot

on:
  pull_request:

jobs:
  run-bugster-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Use Bugster Bot action
        uses: ./.github/actions/bugster
        with:
          ATLASSIAN_API_TOKEN: ${{ secrets.ATLASSIAN_API_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
